### ISSUE TITLE
Smithbox keeps crashing when accessing weapon params in EquipParamWeapon

### ISSUE THREAD

**Issue by DLuong79** [vawser/Smithbox#100]
I keep getting this error when trying to check weapon params (not changing them, just clicking on them). I didn't notice at first because I was only working with bullets beforehand. It might also occur in other categories, but I haven't checked them all yet.

```
Smithbox - Version 1.0.18.1

Index was outside the bounds of the array.

   at Veldrid.Texture.TransitionImageLayout(VkCommandBuffer cb, UInt32 baseMipLevel, UInt32 levelCount, UInt32 baseArrayLayer, UInt32 layerCount, VkImageLayout newLayout) in ./src/Veldrid/Veldrid/Texture.cs:line 341
   at Veldrid.GraphicsDevice.TransitionImageLayout(Texture texture, VkImageLayout layout) in ./src/Veldrid/Veldrid/GraphicsDevice.cs:line 2300
   at Veldrid.Texture.TransitionIfSampled() in ./src/Veldrid/Veldrid/Texture.cs:line 290
   at Veldrid.Texture..ctor(GraphicsDevice gd, TextureDescription& description) in ./src/Veldrid/Veldrid/Texture.cs:line 221
   at Veldrid.ResourceFactory.CreateTextureCore(TextureDescription& description) in ./src/Veldrid/Veldrid/ResourceFactory.cs:line 224
   at Veldrid.ResourceFactory.CreateTexture(TextureDescription& description) in ./src/Veldrid/Veldrid/ResourceFactory.cs:line 159
   at Veldrid.ResourceFactory.CreateTexture(TextureDescription description) in ./src/Veldrid/Veldrid/ResourceFactory.cs:line 150
   at StudioCore.Scene.TexturePool.TextureHandle.FillWithTPF(GraphicsDevice d, CommandList cl, TPFPlatform platform, Texture tex, String name) in ./src/StudioCore/Scene/TexturePool.cs:line 495
   at StudioCore.Resource.TextureResource.<_LoadTexture>b__11_0(GraphicsDevice d, CommandList cl) in ./src/StudioCore/Resource/TextureResource.cs:line 64
   at StudioCore.Scene.Renderer.Frame(CommandList drawCommandList, Boolean backgroundOnly) in ./src/StudioCore/Scene/Renderer.cs:line 160
   at StudioCore.Graphics.VulkanGraphicsContext.Draw(List`1 editors, EditorScreen focusedEditor) in ./src/StudioCore/Graphics/VulkanGraphicsContext.cs:line 119
   at StudioCore.Smithbox.Run() in ./src/StudioCore/Smithbox.cs:line 349
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 36
```

**Comment by vawser** [comment]
The image preview feature is failing to create the texture. You can display the Image Preview in the param editor by toggling it off in the settings, which should prevent this issue.

**Comment by DLuong79** [comment]
Thanks, it worked! Just wondering though: what's the "intended use case" for the Image Preview in the param editor?

**Comment by vawser** [comment]
It shows you the icon image for weapons, armor, etc. Normally you'd need to open the icon image itself (which is packed into a DCX container) and reference the icon ID to the position of the icon in the texture atlas.
