### ISSUE TITLE
Crash on trying to export any text.

### ISSUE THREAD

**Issue by rurattee** [vawser/Smithbox#106]
![Smithbox_UWRW2cxtIq](https://github.com/user-attachments/assets/6d887f12-dee4-4aa1-9b52-f89d7d321696)

Not quite sure what's going on since it looks like a similar issue was fixed previously. Whenever I try to export text, modded or otherwise I get the error in the image above. Since it was a path error I assumed it may have had to do with folder hierarchy, so I tried nesting a text folder in the project. I also thought it may have been the spaces in the filepath but it seems like that wasn't it either. Not really sure what's up but let me know if it's an easy fix on my end.

Path(?):
`F:\Eldo Rang Mods\ModEngine-2.1.0.0-win64-DLC\mod\1Zipped\clever\text`
`clever` being the project directory.

Crash log dump:
```Smithbox - Version 1.0.18.2

Value cannot be null. (Parameter 'path')

   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access)
   at SoulsFormats.MountedSoulsFile`1.Read(String path) in ./src/Andre/SoulsFormats/SoulsFormats/Util/MountedSoulsFile.cs:line 40
   at StudioCore.Editors.TextEditor.FMGLanguage.SaveFMGsNormal() in ./src/StudioCore/Editors/TextEditor/FMGLanguage.cs:line 203
   at StudioCore.Editors.TextEditor.FMGLanguage.SaveFMGs() in ./src/StudioCore/Editors/TextEditor/FMGLanguage.cs:line 129
   at StudioCore.TextEditor.FMGBank.SaveFMGs() in ./src/StudioCore/Editors/TextEditor/FMGBank.cs:line 115
   at StudioCore.TextEditor.TextEditorScreen.SaveAll() in ./src/StudioCore/Editors/TextEditor/TextEditorScreen.cs:line 423
   at StudioCore.Core.EditorHandler.SaveAllFocusedEditor() in ./src/StudioCore/Core/EditorHandler.cs:line 120
   at StudioCore.Smithbox.AttemptSaveOnCrash() in ./src/StudioCore/Smithbox.cs:line 479
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 40
```

**Comment by vawser** [comment]
It's failing to read the FMG binder. Looking at the code in that section, it might be that you don't have the dlc02 FMG binder unpacked (you need to use the latest UXM Selective to unpack it)

**Comment by rurattee** [comment]
That looks to have been it (or at least there's no more crashes and I'm seeing lots of json files in my specified directory). Thanks a million!
