### ISSUE TITLE
No Physical Devices Exist - Smithbox` - Version 1.0.19

### ISSUE THREAD

**Issue by xovielx** [vawser/Smithbox#114]
Recently started getting this error after updating Video Card Drivers. I've tried previous versions, and they don't work either.

```
Smithbox` - Version 1.0.19

No physical devices exist.

   at Veldrid.GraphicsDevice.CreatePhysicalDevice() in ./src/Veldrid/Veldrid/GraphicsDevice.cs:line 1748
   at Veldrid.GraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions) in ./src/Veldrid/Veldrid/GraphicsDevice.cs:line 203
   at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription, VulkanDeviceOptions vkOptions) in ./src/Veldrid/Veldrid/GraphicsDevice.cs:line 2401
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb) in ./src/Veldrid/Veldrid.StartupUtilities/VeldridStartup.cs:line 135
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window) in ./src/Veldrid/Veldrid.StartupUtilities/VeldridStartup.cs:line 119
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options) in ./src/Veldrid/Veldrid.StartupUtilities/VeldridStartup.cs:line 86
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, Sdl2Window& window, GraphicsDevice& gd) in ./src/Veldrid/Veldrid.StartupUtilities/VeldridStartup.cs:line 31
   at StudioCore.Graphics.VulkanGraphicsContext.Initialize() in ./src/StudioCore/Graphics/VulkanGraphicsContext.cs:line 58
   at StudioCore.Smithbox..ctor(IGraphicsContext context, String version) in ./src/StudioCore/Smithbox.cs:line 95
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 32

```

**Comment by vawser** [comment]
Seems like an issue with your graphics card not being recognized. Check that your computer hasn't defaulted to the in-built GPU (if it exists), that can happen sometimes when you update GPU drivers.

**Comment by xovielx** [comment]
Reinstalling the drivers worked perfectly. Thank you.

**Comment by drachenkurve** [comment]
For someone has laptop with AMD iGPU and NVIDIA GPU (with Windows), follow these steps.

1. Change graphics processor for Smithbox to GPU.
2. Create system environment variable `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1` and set value to `1`.

* `Veldrid.GraphicsDevice.CreatePhysicalDevice` uses `vkEnumeratePhysicalDevices`.
* It seems Vulkan can't find a device in this case with default settings.
* reference: https://nvidia.custhelp.com/app/answers/detail/a_id/5182
