### ISSUE TITLE
Crashes when trying to load "Northern Limit 1" in Demon's Souls

### ISSUE THREAD

**Issue by thegreatgramcracker** [vawser/Smithbox#151]
The program seems to crash due to the textures resources in the first Northern Limit map, m07_00_00_00. This crash actually happened previously in DSMapStudio, but only occurred if you enabled textures. Yet, in the current version of Smithbox it crashes even without textures enabled. Crash log below.

```
Smithbox - Version 1.0.23

Specified argument was out of the range of valid values.

   at StudioCore.Scene.TexturePool.TextureHandle.FillWithTPF(GraphicsDevice d, CommandList cl, TPFPlatform platform, Texture tex, String name) in ./src/StudioCore/Scene/TexturePool.cs:line 496
   at StudioCore.Resource.Types.TextureResource.<_LoadTexture>b__11_0(GraphicsDevice d, CommandList cl) in ./src/StudioCore/Resource/Types/TextureResource.cs:line 60
   at StudioCore.Scene.Renderer.Frame(CommandList drawCommandList, Boolean backgroundOnly) in ./src/StudioCore/Scene/Renderer.cs:line 160
   at StudioCore.Graphics.VulkanGraphicsContext.Draw(List`1 editors, EditorScreen focusedEditor) in ./src/StudioCore/Graphics/VulkanGraphicsContext.cs:line 122
   at StudioCore.Smithbox.Run() in ./src/StudioCore/Smithbox.cs:line 365
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 36
```

**Comment by thegreatgramcracker** [comment]
Hello, sorry, this was due to modded files. Seems to work when I fixed the error with my files
