### ISSUE TITLE
Crashing when hovering over data>export in the text editor

### ISSUE THREAD

**Issue by jjiiB** [vawser/Smithbox#152]
![image_2024-11-23_082557571](https://github.com/user-attachments/assets/455be5f1-4415-4fff-9ee2-43743eb99d7e)

**Comment by jjiiB** [comment]
Smithbox - Version 1.0.23

Object reference not set to an instance of an object.

   at StudioCore.Editors.TextEditor.FmgImporter.MenubarOptions() in ./src/StudioCore/Editors/TextEditor/Data/FmgImporter.cs:line 45
   at StudioCore.TextEditor.TextEditorScreen.EditorUniqueDropdowns() in ./src/StudioCore/Editors/TextEditor/TextEditorScreen.cs:line 190
   at StudioCore.Smithbox.Update(Single deltaseconds) in ./src/StudioCore/Smithbox.cs:line 512
   at StudioCore.Smithbox.Run() in ./src/StudioCore/Smithbox.cs:line 353
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 36

**Comment by jjiiB** [comment]
Also with another project i am able to use the export, the project file that breaks is clevers moveset with like 5 other params edited for fp regen

**Comment by vawser** [comment]
It happens if you don't select a File or Text File I believe. It's been fixed for the next release.
