### ISSUE TITLE
[Bug] Map Editor: Crash when trying to right click -> copy rotation or translation properties of an object

### ISSUE THREAD

**Issue by Nereithr** [vawser/Smithbox#154]
Title. Trying to right click copy rotation and translation properties of an object results in a crash, with the following crash log:

```
Smithbox - Version 1.0.23

Object does not match target type.

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at StudioCore.Editors.MapEditor.PropertyEditor.PropAction_Position.CopyCurrentPosition(PropertyInfo prop, Object obj) in ./src/StudioCore/Editors/MapEditor/PropertyEditor/PropAction_Position.cs:line 16
   at StudioCore.Editors.MapEditor.MapPropertyEditor.DisplayPropContextMenu(ViewportSelection selection, PropertyInfo prop, Object obj, Int32 arrayIndex) in ./src/StudioCore/Editors/MapEditor/MapPropertyEditor.cs:line 783
   at StudioCore.Editors.MapEditor.MapPropertyEditor.PropEditorGeneric(ViewportSelection selection, IEnumerable`1 entSelection, Object obj, Int32 classIndex)
   at StudioCore.Editors.MapEditor.MapPropertyEditor.PropEditorSelectedEntities(ViewportSelection selection, Int32 classIndex) in ./src/StudioCore/Editors/MapEditor/MapPropertyEditor.cs:line 1129
   at StudioCore.Editors.MapEditor.MapEditorScreen.OnGUI(String[] initcmd) in ./src/StudioCore/Editors/MapEditor/MapEditorScreen.cs:line 911
   at StudioCore.Smithbox.Update(Single deltaseconds) in ./src/StudioCore/Smithbox.cs:line 591
   at StudioCore.Smithbox.Run() in ./src/StudioCore/Smithbox.cs:line 353
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 36
```

All dependencies are installed, ER is version 1.16.

**Comment by vawser** [comment]
Should be fixed for the next release.
