### ISSUE TITLE
Crashing to Whitescreen

### ISSUE THREAD

**Issue by FinallyRage** [vawser/Smithbox#24]
I was trying to view some text and suddenly the app crashed and gave me this crash report.

I can't find any way to reset the selections or where it maybe stored.  I show nothing in %appdata% and trying a new install causes the same error.  I tried to revert to a previous version and got the same error.

The network path was not found. : '\\.smithbox\ER\selections'

   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at StudioCore.Banks.SelectionGroupBank.SelectionGroupBank.CreateSelectionGroups() in ./src/StudioCore/Banks/SelectionGroupBank/SelectionGroupBank.cs:line 51
   at StudioCore.Smithbox..ctor(IGraphicsContext context, String version) in ./src/StudioCore/Smithbox.cs:line 106
   at Smithbox_LowRequirements.Program.Main(String[] args) in ./src/Studio.App/Smithbox_LowRequirements/Program.cs:line 27

**Comment by PWDK233** [comment]
me too,yestoday is work,but today i cant use it

Smithbox - Version 1.0.12.1

The network path was not found. : '\\.smithbox\ER\selections'

   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at StudioCore.Banks.SelectionGroupBank.SelectionGroupBank.CreateSelectionGroups() in ./src/StudioCore/Banks/SelectionGroupBank/SelectionGroupBank.cs:line 54
   at StudioCore.Smithbox..ctor(IGraphicsContext context, String version) in ./src/StudioCore/Smithbox.cs:line 106
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 32

**Comment by vawser** [comment]
This seems to happen if a project.json is created in a drive root, like C://. If you look in such locations, delete the existing project.json and then re-launch Smithbox, you should be able to create a new project.

**Comment by PWDK233** [comment]
> This seems to happen if a project.json is created in a drive root, like C://. If you look in such locations, delete the existing project.json and then re-launch Smithbox, you should be able to create a new project.

yes!!!!!!!!!!!!!!   i Del D://project.json and is work   TY

**Comment by vawser** [comment]
I've added some safeguards to prevent this accidently happening in the next release.
