### ISSUE TITLE
Error after attempt to launch. :c

### ISSUE THREAD

**Issue by BROKETHEWITCH** [vawser/Smithbox#36]
Error message
`An item with the same key has already been added. Key: [, StudioCore.Editors.TextureViewer.TextureFolderBank+TextureViewInfo]`

This is right after launching the program. All 3 required programs have been installed.

**Comment by BROKETHEWITCH** [comment]
Smithbox - Version 1.0.14.4

An item with the same key has already been added. Key: [, StudioCore.Editors.TextureViewer.TextureFolderBank+TextureViewInfo]

   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedSet`1.Add(T item)
   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
   at StudioCore.Editors.TextureViewer.TextureFolderBank.AddTextureFolder(String path, TextureViewCategory category, Boolean isModFile) in ./src/StudioCore/Editors/TextureViewer/TextureFolderBank.cs:line 310
   at StudioCore.Editors.TextureViewer.TextureFolderBank.FindTextureFolder(String folderDir, String fileExt, TextureViewCategory category) in ./src/StudioCore/Editors/TextureViewer/TextureFolderBank.cs:line 284
   at StudioCore.Editors.TextureViewer.TextureFolderBank.ScanPartsFolder(TextureViewCategory category) in ./src/StudioCore/Editors/TextureViewer/TextureFolderBank.cs:line 193
   at StudioCore.Editors.TextureViewer.TextureFolderBank.LoadTextureFolders() in ./src/StudioCore/Editors/TextureViewer/TextureFolderBank.cs:line 52
   at StudioCore.TextureViewer.TextureViewerScreen.OnGUI(String[] initcmd) in ./src/StudioCore/Editors/TextureViewer/TextureViewerScreen.cs:line 220
   at StudioCore.Smithbox.Update(Single deltaseconds) in ./src/StudioCore/Smithbox.cs:line 617
   at StudioCore.Smithbox.Run() in ./src/StudioCore/Smithbox.cs:line 327
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 36

**Comment by vawser** [comment]
I'll look into this, looks like a missing condition before the dictionary add. Might be due to the new update too.

**Comment by BROKETHEWITCH** [comment]
Ok thanks. I'll just wait for update.
