### ISSUE TITLE
Error on second Launch

### ISSUE THREAD

**Issue by Jumper2105** [vawser/Smithbox#65]
Smithbox - Version 1.0.12

Der Netzwerkpfad wurde nicht gefunden. : '\\.smithbox\ER\selections'

   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at StudioCore.Banks.SelectionGroupBank.SelectionGroupBank.CreateSelectionGroups() in ./src/StudioCore/Banks/SelectionGroupBank/SelectionGroupBank.cs:line 51
   at StudioCore.Smithbox..ctor(IGraphicsContext context, String version) in ./src/StudioCore/Smithbox.cs:line 106
   at Smithbox.Program.Main(String[] args) in ./src/Studio.App/Smithbox/Program.cs:line 32

**Comment by vawser** [comment]
You should update to the latest version, this issue should be fixed if you do that.
